version: '3.8'

services:
  backend:
    image: wlsgusan/gymggun_backend:latest
    container_name: gymggun_backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file: .env
    command: ["--spring.profiles.active=local"]

