--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12 (Debian 15.12-1.pgdg120+1)
-- Dumped by pg_dump version 15.12 (Debian 15.12-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    content text NOT NULL,
    role character varying(20) NOT NULL,
    member_id bigint
);


ALTER TABLE public.chat_message OWNER TO postgres;

--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.chat_message_id_seq OWNER TO postgres;

--
-- Name: chat_message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.chat_message_id_seq OWNED BY public.chat_message.id;


--
-- Name: diet_plans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diet_plans (
    id bigint NOT NULL,
    diet_type character varying(50),
    breakfast text,
    lunch text,
    dinner text,
    user_gender character varying(10) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone
);


ALTER TABLE public.diet_plans OWNER TO postgres;

--
-- Name: diet_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.diet_plans_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.diet_plans_id_seq OWNER TO postgres;

--
-- Name: diet_plans_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.diet_plans_id_seq OWNED BY public.diet_plans.id;


--
-- Name: exercise; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise (
    id bigint NOT NULL,
    distance integer NOT NULL,
    name character varying(255),
    reps integer NOT NULL,
    exercise_type character varying(255)
);


ALTER TABLE public.exercise OWNER TO postgres;

--
-- Name: exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercise_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise_record (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    exercise_id bigint,
    member_id bigint,
    date timestamp(6) without time zone,
    memo_data jsonb,
    record_data jsonb
);


ALTER TABLE public.exercise_record OWNER TO postgres;

--
-- Name: exercise_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercise_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercise_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_nutrition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_nutrition (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    calories double precision NOT NULL,
    protein double precision NOT NULL,
    carbs double precision NOT NULL,
    fat double precision NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone
);


ALTER TABLE public.food_nutrition OWNER TO postgres;

--
-- Name: food_nutrition_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.food_nutrition_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.food_nutrition_id_seq OWNER TO postgres;

--
-- Name: food_nutrition_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.food_nutrition_id_seq OWNED BY public.food_nutrition.id;


--
-- Name: inbody; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inbody (
    inbody_id bigint NOT NULL,
    bmi integer,
    date character varying(255),
    tall integer,
    weight integer,
    member_id bigint
);


ALTER TABLE public.inbody OWNER TO postgres;

--
-- Name: inbody_inbody_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.inbody_inbody_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.inbody_inbody_id_seq OWNER TO postgres;

--
-- Name: inbody_inbody_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.inbody_inbody_id_seq OWNED BY public.inbody.inbody_id;


--
-- Name: meal_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meal_records (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    food_name character varying(255) NOT NULL,
    portion double precision NOT NULL,
    unit character varying(10) NOT NULL,
    meal_date date DEFAULT CURRENT_DATE NOT NULL,
    meal_time time without time zone DEFAULT CURRENT_TIME,
    meal_type character varying(10) NOT NULL,
    calories double precision NOT NULL,
    protein double precision NOT NULL,
    carbs double precision NOT NULL,
    fat double precision NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    CONSTRAINT meal_records_meal_type_check CHECK (((meal_type)::text = ANY ((ARRAY['아침'::character varying, '점심'::character varying, '저녁'::character varying, '간식'::character varying])::text[])))
);


ALTER TABLE public.meal_records OWNER TO postgres;

--
-- Name: meal_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.meal_records_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.meal_records_id_seq OWNER TO postgres;

--
-- Name: meal_records_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.meal_records_id_seq OWNED BY public.meal_records.id;


--
-- Name: member; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member (
    member_id integer NOT NULL,
    name character varying(50) NOT NULL,
    gender character varying(1) NOT NULL,
    height numeric(5,2),
    weight numeric(5,2),
    birth date,
    goal text,
    etc text,
    phone_number character varying(20),
    tcm_token character varying(255),
    temp_id character varying(100),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id bigint NOT NULL,
    modified_at timestamp without time zone,
    email character varying(255),
    fcm_token character varying(255),
    password character varying(255),
    phone character varying(255),
    profile_image character varying(255),
    CONSTRAINT member_gender_check CHECK (((gender)::text = ANY ((ARRAY['M'::character varying, 'F'::character varying])::text[])))
);


ALTER TABLE public.member OWNER TO postgres;

--
-- Name: member_goal_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member_goal_list (
    email bigint NOT NULL,
    goal character varying(255),
    CONSTRAINT member_goal_list_goal_check CHECK (((goal)::text = ANY ((ARRAY['WEIGHT_LOSS'::character varying, 'STRENGTH'::character varying, 'MENTAL_HEALTH'::character varying, 'HEALTH_MAINTENANCE'::character varying, 'BODY_SHAPE'::character varying, 'HOBBY'::character varying])::text[])))
);


ALTER TABLE public.member_goal_list OWNER TO postgres;

--
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.member_id_seq OWNER TO postgres;

--
-- Name: member_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.member_id_seq OWNED BY public.member.id;


--
-- Name: member_member_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.member_member_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.member_member_id_seq OWNER TO postgres;

--
-- Name: member_member_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.member_member_id_seq OWNED BY public.member.member_id;


--
-- Name: member_role_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member_role_list (
    email bigint NOT NULL,
    role character varying(255),
    CONSTRAINT member_role_list_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'TRAINER'::character varying])::text[])))
);


ALTER TABLE public.member_role_list OWNER TO postgres;

--
-- Name: pt_contract; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pt_contract (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    end_date timestamp(6) without time zone,
    memo character varying(255),
    start_date timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    total_count integer NOT NULL,
    used_count integer NOT NULL,
    member_id bigint,
    trainer_id bigint,
    CONSTRAINT pt_contract_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'SUSPENDED'::character varying, 'EXPIRED'::character varying])::text[])))
);


ALTER TABLE public.pt_contract OWNER TO postgres;

--
-- Name: pt_contract_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pt_contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pt_contract_id_seq OWNER TO postgres;

--
-- Name: pt_contract_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pt_contract_id_seq OWNED BY public.pt_contract.id;


--
-- Name: pt_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pt_log (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    created_by bigint NOT NULL,
    feedback character varying(255),
    injury_check boolean,
    modified_by bigint,
    next_plan character varying(255),
    member_id bigint,
    pt_schedule_id bigint
);


ALTER TABLE public.pt_log OWNER TO postgres;

--
-- Name: pt_log_exercise; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pt_log_exercise (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    feedback character varying(255),
    reps integer NOT NULL,
    rest_time integer,
    sequence integer NOT NULL,
    sets integer NOT NULL,
    weight integer NOT NULL,
    exercise_id bigint,
    pt_log_id bigint
);


ALTER TABLE public.pt_log_exercise OWNER TO postgres;

--
-- Name: pt_log_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pt_log_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pt_log_exercise_id_seq OWNER TO postgres;

--
-- Name: pt_log_exercise_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pt_log_exercise_id_seq OWNED BY public.pt_log_exercise.id;


--
-- Name: pt_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pt_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pt_log_id_seq OWNER TO postgres;

--
-- Name: pt_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pt_log_id_seq OWNED BY public.pt_log.id;


--
-- Name: pt_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pt_schedule (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    end_time timestamp(6) without time zone NOT NULL,
    reason character varying(255),
    reservation_id character varying(255),
    start_time timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    pt_contract_id bigint,
    CONSTRAINT pt_schedule_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'NO_SHOW'::character varying])::text[])))
);


ALTER TABLE public.pt_schedule OWNER TO postgres;

--
-- Name: pt_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pt_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pt_schedule_id_seq OWNER TO postgres;

--
-- Name: pt_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pt_schedule_id_seq OWNED BY public.pt_schedule.id;


--
-- Name: subscribe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscribe (
    id bigint NOT NULL,
    management_person character varying(255),
    name character varying(255),
    price character varying(255),
    trainer_id bigint
);


ALTER TABLE public.subscribe OWNER TO postgres;

--
-- Name: subscribe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.subscribe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.subscribe_id_seq OWNER TO postgres;

--
-- Name: subscribe_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.subscribe_id_seq OWNED BY public.subscribe.id;


--
-- Name: trainer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trainer (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    career character varying(255),
    certification character varying(255),
    email character varying(255),
    fcm_token character varying(255),
    introduction character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255),
    profile_image character varying(255),
    speciality character varying(255),
    user_type character varying(255) NOT NULL
);


ALTER TABLE public.trainer OWNER TO postgres;

--
-- Name: trainer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.trainer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.trainer_id_seq OWNER TO postgres;

--
-- Name: trainer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.trainer_id_seq OWNED BY public.trainer.id;


--
-- Name: user_diet_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_diet_info (
    user_id integer,
    activity_level character varying(50),
    allergies text,
    dietary_preference character varying(50),
    meal_pattern character varying(50),
    meal_times text,
    food_preferences text,
    special_requirements text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id bigint NOT NULL,
    modified_at timestamp without time zone,
    member_id bigint
);


ALTER TABLE public.user_diet_info OWNER TO postgres;

--
-- Name: user_diet_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_diet_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_diet_info_id_seq OWNER TO postgres;

--
-- Name: user_diet_info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_diet_info_id_seq OWNED BY public.user_diet_info.id;


--
-- Name: chat_message id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message ALTER COLUMN id SET DEFAULT nextval('public.chat_message_id_seq'::regclass);


--
-- Name: diet_plans id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diet_plans ALTER COLUMN id SET DEFAULT nextval('public.diet_plans_id_seq'::regclass);


--
-- Name: food_nutrition id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_nutrition ALTER COLUMN id SET DEFAULT nextval('public.food_nutrition_id_seq'::regclass);


--
-- Name: inbody inbody_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inbody ALTER COLUMN inbody_id SET DEFAULT nextval('public.inbody_inbody_id_seq'::regclass);


--
-- Name: meal_records id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_records ALTER COLUMN id SET DEFAULT nextval('public.meal_records_id_seq'::regclass);


--
-- Name: member member_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member ALTER COLUMN member_id SET DEFAULT nextval('public.member_member_id_seq'::regclass);


--
-- Name: member id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member ALTER COLUMN id SET DEFAULT nextval('public.member_id_seq'::regclass);


--
-- Name: pt_contract id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_contract ALTER COLUMN id SET DEFAULT nextval('public.pt_contract_id_seq'::regclass);


--
-- Name: pt_log id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_log ALTER COLUMN id SET DEFAULT nextval('public.pt_log_id_seq'::regclass);


--
-- Name: pt_log_exercise id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_log_exercise ALTER COLUMN id SET DEFAULT nextval('public.pt_log_exercise_id_seq'::regclass);


--
-- Name: pt_schedule id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_schedule ALTER COLUMN id SET DEFAULT nextval('public.pt_schedule_id_seq'::regclass);


--
-- Name: subscribe id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscribe ALTER COLUMN id SET DEFAULT nextval('public.subscribe_id_seq'::regclass);


--
-- Name: trainer id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainer ALTER COLUMN id SET DEFAULT nextval('public.trainer_id_seq'::regclass);


--
-- Name: user_diet_info id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_diet_info ALTER COLUMN id SET DEFAULT nextval('public.user_diet_info_id_seq'::regclass);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: diet_plans diet_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diet_plans
    ADD CONSTRAINT diet_plans_pkey PRIMARY KEY (id);


--
-- Name: exercise exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise
    ADD CONSTRAINT exercise_pkey PRIMARY KEY (id);


--
-- Name: exercise_record exercise_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_record
    ADD CONSTRAINT exercise_record_pkey PRIMARY KEY (id);


--
-- Name: food_nutrition food_nutrition_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_nutrition
    ADD CONSTRAINT food_nutrition_name_key UNIQUE (name);


--
-- Name: food_nutrition food_nutrition_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_nutrition
    ADD CONSTRAINT food_nutrition_pkey PRIMARY KEY (id);


--
-- Name: inbody inbody_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inbody
    ADD CONSTRAINT inbody_pkey PRIMARY KEY (inbody_id);


--
-- Name: meal_records meal_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_records
    ADD CONSTRAINT meal_records_pkey PRIMARY KEY (id);


--
-- Name: member member_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_phone_number_key UNIQUE (phone_number);


--
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (member_id);


--
-- Name: member member_tcm_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_tcm_token_key UNIQUE (tcm_token);


--
-- Name: member member_temp_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_temp_id_key UNIQUE (temp_id);


--
-- Name: pt_contract pt_contract_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_contract
    ADD CONSTRAINT pt_contract_pkey PRIMARY KEY (id);


--
-- Name: pt_log_exercise pt_log_exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_log_exercise
    ADD CONSTRAINT pt_log_exercise_pkey PRIMARY KEY (id);


--
-- Name: pt_log pt_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_log
    ADD CONSTRAINT pt_log_pkey PRIMARY KEY (id);


--
-- Name: pt_schedule pt_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_schedule
    ADD CONSTRAINT pt_schedule_pkey PRIMARY KEY (id);


--
-- Name: subscribe subscribe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscribe
    ADD CONSTRAINT subscribe_pkey PRIMARY KEY (id);


--
-- Name: trainer trainer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainer
    ADD CONSTRAINT trainer_pkey PRIMARY KEY (id);


--
-- Name: trainer uk_4jrvips0u6okch0ktcu7xdaxw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainer
    ADD CONSTRAINT uk_4jrvips0u6okch0ktcu7xdaxw UNIQUE (email);


--
-- Name: subscribe uk_cwiu1ltiudy55xuvyio54y9yi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscribe
    ADD CONSTRAINT uk_cwiu1ltiudy55xuvyio54y9yi UNIQUE (trainer_id);


--
-- Name: pt_log fk31pvy4ftcjj0jpiwybnx0m8g2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_log
    ADD CONSTRAINT fk31pvy4ftcjj0jpiwybnx0m8g2 FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: user_diet_info fk3vo8614mvcgxwile7nceblf76; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_diet_info
    ADD CONSTRAINT fk3vo8614mvcgxwile7nceblf76 FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: pt_log_exercise fk5cwfd6u1i5toqkm1ka4drwsih; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_log_exercise
    ADD CONSTRAINT fk5cwfd6u1i5toqkm1ka4drwsih FOREIGN KEY (exercise_id) REFERENCES public.exercise(id);


--
-- Name: exercise_record fk7fiyqujs2rgonrrrd7j253pvd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_record
    ADD CONSTRAINT fk7fiyqujs2rgonrrrd7j253pvd FOREIGN KEY (exercise_id) REFERENCES public.exercise(id);


--
-- Name: exercise_record fk8fa64togt2369kaeyi9lvpf9l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_record
    ADD CONSTRAINT fk8fa64togt2369kaeyi9lvpf9l FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: member_goal_list fk8mj1ps4ih0l8reb2k0l2d87pk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_goal_list
    ADD CONSTRAINT fk8mj1ps4ih0l8reb2k0l2d87pk FOREIGN KEY (email) REFERENCES public.member(member_id);


--
-- Name: pt_schedule fkao87ivonc67c5gjbdnw7qiejv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_schedule
    ADD CONSTRAINT fkao87ivonc67c5gjbdnw7qiejv FOREIGN KEY (pt_contract_id) REFERENCES public.pt_contract(id);


--
-- Name: pt_log_exercise fkgisxj5onkhyfl251xmem75pwc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_log_exercise
    ADD CONSTRAINT fkgisxj5onkhyfl251xmem75pwc FOREIGN KEY (pt_log_id) REFERENCES public.pt_log(id);


--
-- Name: subscribe fkhqt1r63276yyytauqgekvwodu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscribe
    ADD CONSTRAINT fkhqt1r63276yyytauqgekvwodu FOREIGN KEY (trainer_id) REFERENCES public.trainer(id);


--
-- Name: inbody fkmd9yjuua2pncmdfq0lyk6d5qc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inbody
    ADD CONSTRAINT fkmd9yjuua2pncmdfq0lyk6d5qc FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: pt_log fkmj4wc1qkahfevdx2ecjr5l6jv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_log
    ADD CONSTRAINT fkmj4wc1qkahfevdx2ecjr5l6jv FOREIGN KEY (pt_schedule_id) REFERENCES public.pt_schedule(id);


--
-- Name: pt_contract fknaoq3t7fukij0otbuhponrktx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_contract
    ADD CONSTRAINT fknaoq3t7fukij0otbuhponrktx FOREIGN KEY (trainer_id) REFERENCES public.trainer(id);


--
-- Name: pt_contract fkr57gnud3pqvfct4bq8akdi7nu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pt_contract
    ADD CONSTRAINT fkr57gnud3pqvfct4bq8akdi7nu FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: chat_message fkynfbnbqot8mpd1tquoc2s1w5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT fkynfbnbqot8mpd1tquoc2s1w5 FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: meal_records meal_records_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_records
    ADD CONSTRAINT meal_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.member(member_id) ON DELETE CASCADE;


--
-- Name: user_diet_info user_diet_info_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_diet_info
    ADD CONSTRAINT user_diet_info_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.member(member_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

