name: Deploy To EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: final_project_be

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > src/.env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "[1] 이동: 프로젝트 디렉토리로"
            cd /home/ubuntu/${{ env.REPOSITORY_NAME }}

            echo "[2] 권한 설정"
            sudo chown -R ubuntu:ubuntu .

            echo "[3] 코드 최신화"
            git pull origin dev

            echo "[4] 빌드 실행"
            chmod +x ./gradlew
            ./gradlew clean build -x test

            echo "[5] 포트 종료 및 애플리케이션 재실행"
            sudo fuser -k -n tcp 8081 || true
            nohup java -jar build/libs/*SNAPSHOT.jar \
              --spring.profiles.active=local > output.log 2>&1 &
